name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: package-lock-${{ hashFiles('package-lock.json') }}
          restore-keys: package-lock-

      - name: Install dependencies
        run: npm ci

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: npm run publish
