on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
      - name: Checkout Repo
        uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 20
        if: ${{ steps.release.outputs.release_created }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: package-lock-${{ hashFiles('package-lock.json') }}
          restore-keys: package-lock-
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npm run publish
        if: ${{ steps.release.outputs.release_created }}
